INSERT INTO Customer (FirstName, LastName, CCLast4, PlanType, LastPayment, NextPayment) VALUES
('James', 'Smith', '1234', 'Medium', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
('Mary', 'Johnson', '5678', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Robert', 'Williams', '9012', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 15 DAY)),
('Patricia', 'Brown', '3456', 'Medium', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), DATE_SUB(CURDATE(), INTERVAL 2 MONTH)),
('Michael', 'Jones', '7890', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Linda', 'Garcia', '2345', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 5 DAY)),
('William', 'Miller', '6789', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Barbara', 'Davis', '0123', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), DATE_SUB(CURDATE(), INTERVAL 3 MONTH)),
('David', 'Martinez', '4567', 'Cajun Hot', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 20 DAY)),
('Susan', 'Anderson', '8901', 'Medium', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 5 DAY)),
('Richard', 'Taylor', '2346', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
('Jessica', 'Thomas', '6780', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Joseph', 'Jackson', '0124', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), DATE_SUB(CURDATE(), INTERVAL 4 MONTH)),
('Sarah', 'White', '4568', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Thomas', 'Harris', '8902', 'Medium', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 10 DAY)),
('Karen', 'Martin', '2347', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), DATE_SUB(CURDATE(), INTERVAL 2 MONTH)),
('Charles', 'Thompson', '6781', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Nancy', 'Garcia', '0125', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 10 DAY)),
('Christopher', 'Moore', '4569', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Lisa', 'Jackson', '8903', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 3 DAY)),
('Daniel', 'Lee', '2348', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), DATE_SUB(CURDATE(), INTERVAL 5 MONTH)),
('Betty', 'Perez', '6782', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Matthew', 'Clark', '0126', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
('Margaret', 'Lewis', '4560', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 25 DAY)),
('Anthony', 'Robinson', '8904', 'Medium', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), DATE_SUB(CURDATE(), INTERVAL 3 MONTH)),
('Sandra', 'Walker', '2349', 'Cajun Hot', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Mark', 'Hall', '6783', 'Medium', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 7 DAY)),
('Ashley', 'Allen', '0127', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), DATE_SUB(CURDATE(), INTERVAL 2 MONTH)),
('Donald', 'Young', '4561', 'Cajun Hot', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Donna', 'Hernandez', '8905', 'Medium', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 15 DAY)),
('Steven', 'King', '2340', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Dorothy', 'Wright', '6784', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), DATE_SUB(CURDATE(), INTERVAL 4 MONTH)),
('Paul', 'Lopez', '0128', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Carol', 'Hill', '4562', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 2 DAY)),
('Andrew', 'Scott', '8906', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
('Michelle', 'Green', '2341', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Joshua', 'Adams', '6785', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), DATE_SUB(CURDATE(), INTERVAL 20 DAY)),
('Amanda', 'Baker', '0129', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Kenneth', 'Nelson', '4563', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 12 DAY)),
('Melissa', 'Carter', '8907', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), DATE_SUB(CURDATE(), INTERVAL 3 MONTH)),
('Kevin', 'Mitchell', '2342', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Deborah', 'Perez', '6786', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
('Brian', 'Roberts', '0120', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Stephanie', 'Turner', '4564', 'Medium', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), DATE_ADD(CURDATE(), INTERVAL 8 DAY)),
('George', 'Phillips', '8908', 'Cajun Hot', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), DATE_SUB(CURDATE(), INTERVAL 2 MONTH)),
('Sharon', 'Campbell', '2343', 'Spicy', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Timothy', 'Parker', '6787', 'Medium', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), DATE_SUB(CURDATE(), INTERVAL 4 MONTH)),
('Cynthia', 'Evans', '0121', 'Cajun Hot', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH)),
('Ronald', 'Edwards', '4565', 'Spicy', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), DATE_SUB(CURDATE(), INTERVAL 7 DAY)),
('Angela', 'Collins', '8909', 'Medium', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH));